AdamPriestman/wastenot

- app/models/recipe.rb
> heroku fix

- Gemfile
- Gemfile.lock
- db/seeds.rb
- added faker gem
- added 5 users and 5 recipes (super basic faker seed)
> made seed file

- app/controllers/application_controller.rb
- app/controllers/pages_controller.rb
- app/controllers/recipes_controller.rb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- config/routes.rb
- Added basic routes for search page, recipe index and recipe show
- Added empty html files for the above
- Added user extra columns to sign up and edit user pages
- Added skip authentication for search, index and show pages
> Basic routes and user authentication

- db/migrate/20231128113057_rename_cusine_to_cuisine.rb
- db/migrate/20231128113305_add_description_to_recipes.rb
- db/schema.rb
- corrected spelling cusine => cuisine
- added description field to recipe
> corrected cuisine spelling and added description field

- db/migrate/20231128144746_add_columns_to_recipes.rb
- db/schema.rb
- db/seeds.rb
- added api seeding
- changed recipes schema
> added api seeding

- app/assets/stylesheets/components/_recipe_card.scss
- app/assets/stylesheets/pages/_index.scss
- app/assets/stylesheets/pages/_index_page.scss
- app/views/recipes/_recipe_card.html.erb
- app/views/recipes/index.html.erb
- db/migrate/20231128173035_add_image_to_recipe.rb
- db/schema.rb
- db/seeds.rb
> Index page adam

- app/assets/stylesheets/config/_bootstrap_variables.scss
- app/controllers/pages_controller.rb
- app/controllers/recipes_controller.rb
- app/javascript/controllers/search_form_controller.js
- app/models/recipe.rb
- app/views/pages/search.html.erb
- db/seeds.rb
- Basic search page
- Able to select one ingredient from dropdown
- Set cooktime
- Set servings
> Build your search page

- app/javascript/controllers/search_form_controller.js
- app/views/pages/search.html.erb
- app/views/shared/_search_form.html.erb
Moved search form into partial
> Search page more details

- app/views/pages/search.html.erb
- app/views/shared/_search_form.html.erb
> Move controller

- app/views/recipes/show.html.erb
see others cards in the show page is now clickable & routes to the particular recipe.
> see others card are clickable & routes to the recipe

- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/pages/_index_page.scss
- app/controllers/recipes_controller.rb
- app/javascript/controllers/modal_controller.js
- app/javascript/controllers/toggle_controller.js
- app/views/recipes/_recipe_card.html.erb
- app/views/recipes/index.html.erb
> Index page js adam

- app/controllers/bookmarks_controller.rb
- app/views/bookmarks/index.html.erb
- app/views/recipes/show.html.erb
- config/routes.rb
-Bookmarks create and index method works
-need to fix link on show page
-need to style
-need to change route for bookmarks index
> Bookmarks index method

- app/assets/stylesheets/pages/_search.scss
- app/controllers/recipes_controller.rb
- app/javascript/controllers/search_form_controller.js
- db/seeds.rb
- Added ingredients in seed file
- Improved search form (8+ servings and bugfix)
> Add ingredients to seeds

- app/controllers/posts_controller.rb
- app/views/posts/index.html.erb
- app/views/posts/new.html.erb
- app/views/recipes/show.html.erb
- app/views/shared/_navbar.html.erb
- config/routes.rb
1. reolved the conflict with abshai on bookmark link on show page.
2. community feed is there but no posts yet.
> Community feed

- app/controllers/bookmarks_controller.rb
- app/models/bookmark.rb
- app/views/recipes/show.html.erb
- app/views/shared/_navbar.html.erb
-added link to bookmark icon in navbar
-added validation to prevent users from adding the same recipe
> Bookmark validation

- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- app/models/recipe.rb
- app/models/user.rb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/recipes/_recipe_card.html.erb
- app/views/recipes/show.html.erb
- app/views/shared/_header.html.erb
- app/views/shared/_search_form.html.erb
- config/environments/development.rb
- config/storage.yml
- db/migrate/20231201105443_create_active_storage_tables.active_storage.rb
- db/schema.rb
- db/seeds.rb
-Added cloudinary (you guys will need to add your api keys!)
-Checkboxes are now inside form
> Cloudinary

- app/assets/stylesheets/components/_show.scss
- app/assets/stylesheets/pages/_home.scss
- app/models/ingredient.rb
- app/models/recipe.rb
- app/views/recipes/_recipe_card.html.erb
- app/views/recipes/show.html.erb
- db/migrate/20231201115303_add_average_rating_to_recipes.rb
- db/schema.rb
- db/seeds.rb
- More seeds
- Average rating randomised for recipes
- ingredients displayed on show page
- homepage longer
> Seedfile improve

- Gemfile.lock
- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/pages/_index_page.scss
- app/controllers/recipes_controller.rb
- app/javascript/controllers/index_filter_controller.js
- app/javascript/controllers/modal_controller.js
- app/views/recipes/_filters.html.erb
- app/views/recipes/index.html.erb
- config/environments/production.rb
- modal transition
- checkboxes on the modal now filter the index page correctly
> Index page modal transition friday

- app/assets/stylesheets/config/_fonts.scss
> Font change

- Gemfile.lock
- app/assets/stylesheets/pages/_index_page.scss
- app/assets/stylesheets/pages/_search.scss
- app/controllers/recipes_controller.rb
- app/javascript/controllers/search_form_controller.js
- app/views/recipes/index.html.erb
- app/views/shared/_header.html.erb
- app/views/shared/_search_form.html.erb
- Search page has remove ingredient button
- Searching for things that contain name now
- Fixed header browse all link
> Search page improve

- app/models/recipe.rb
- db/seeds.rb
> Seed posts

- app/javascript/controllers/header_controller.js
-Navbar now only moves once you scroll past it
> No results found

- app/assets/stylesheets/pages/_index_page.scss
- app/views/pages/home.html.erb
- changed banner text
- general styling
> Adam more style

- app/controllers/pages_controller.rb
- app/controllers/recipes_controller.rb
- Removed authentication from search, recipe index and recipe show pages
- Now you have to be logged in, so it doesn't break, it just takes you to the login page
> Removed authentication for search, index and show

- app/assets/stylesheets/components/_show.scss
- app/controllers/posts_controller.rb
- app/views/posts/edit.html.erb
- app/views/posts/new.html.erb
- app/views/recipes/show.html.erb
1. form button is primary green now - both edit & new
2. Average rating method set to display rating in 1decimal place
3. show page post card image fixed now.
> Style form button

- app/assets/stylesheets/components/_recipe_card.scss
- app/models/recipe.rb
- app/views/recipes/_recipe_card.html.erb
- app/views/recipes/index.html.erb
- db/seeds.rb
- added more seeds for recipes
- made truncate on recipe card titles dynamic to the number of icons on the same line
> Adam seed file

- app/views/recipes/show.html.erb
- truncated titles on recipe show page of other recipes you might enjoy so the pic doesnt go over the car edges
> changed other recipes on show page

- app/assets/stylesheets/pages/_home.scss
- app/assets/stylesheets/pages/_search.scss
- All pages now have even margins on the side (in theory..)
- Home page button text centered
> Margins and button centered

- app/assets/stylesheets/pages/_index_page.scss
- app/javascript/controllers/header_controller.js
- app/javascript/controllers/index_filter_controller.js
- app/views/recipes/index.html.erb
- stickiness on filter icon and list count
- removed header from index page
> Stickiness adam

- app/assets/stylesheets/pages/_index_page.scss
- app/javascript/controllers/index_filter_controller.js
- app/javascript/controllers/redirect_controller.js
- app/javascript/controllers/save_url_controller.js
- app/views/recipes/index.html.erb
- app/views/recipes/show.html.erb
- store the url with local storage (basically caching)
- styled filter modal tiny bit
> added storing the url and styled filter modal higher up

- app/assets/stylesheets/components/_filters.scss
- app/assets/stylesheets/config/_bootstrap_variables.scss
- app/assets/stylesheets/pages/_index_page.scss
- app/assets/stylesheets/pages/_search.scss
> Some more colours

- app/assets/stylesheets/components/_bookmark_card.scss
- app/assets/stylesheets/components/_recipe_card.scss
- app/views/bookmarks/_bookmark_card.html.erb
- app/views/recipes/_recipe_card.html.erb
- they see my styling they hating
> matched bookmark card styling to match index card styling

- app/assets/stylesheets/components/_show.scss
- app/assets/stylesheets/config/_fonts.scss
- app/assets/stylesheets/pages/_home.scss
- app/views/pages/home.html.erb
added brand name to home page
on show page other recipe cards fix
> Brand name on homepage

- app/assets/stylesheets/components/_bookmark_card.scss
- app/assets/stylesheets/components/_new_edit_form.scss
- app/assets/stylesheets/components/_recipe_card.scss
- app/assets/stylesheets/components/_show.scss
- app/views/posts/new.html.erb
- app/views/recipes/show.html.erb
> Index page bookmark fix
